import {
  ArrowLeftRight,
  Bot,
  Brain,
  CalendarCheck,
  CarFront,
  Clapperboard,
  Clock,
  Languages,
  Lock,
  MonitorSmartphone,
  QrCode,
  Rocket,
  ScanSearch,
  ShieldCheck,
  Sparkles,
  WifiOff,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { HighlightIcon } from "@/lib/content/projects";

export const highlightIcons: Record<HighlightIcon, LucideIcon> = {
  lock: Lock,
  zap: Zap,
  bot: Bot,
  shield: ShieldCheck,
  workflow: Workflow,
  clock: Clock,
  languages: Languages,
  "wifi-off": WifiOff,
  film: Clapperboard,
  switch: ArrowLeftRight,
  qr: QrCode,
  screens: MonitorSmartphone,
  sparkles: Sparkles,
  rocket: Rocket,
  calendar: CalendarCheck,
  car: CarFront,
  scan: ScanSearch,
  brain: Brain,
};
